### ISSUE TITLE
Add an option to specify the lock TTL timeout

### ISSUE THREAD

**Issue by malkiz-rapid** [gvko/db-migrator-distributed#1]
In the following code segment, it is hard-coded that if the existing lock was acquired more than 1 minute ago - it will be ignored and released.

https://github.com/gvko/db-migrator-distributed/blob/8afd1b631078aeb4581cba6b67071b622488cb37/src/index.ts#L165-L178

I would like to be able to define the time period to be more than 1 minute, because I have some migrations that take longer to finish.

**Comment by gvko** [comment]
Hey @malkiz-rapid . I _might_ have time this week to look into this. 
If it's an urgent issue for you, I gladly accept PRs. :)

**Comment by malkiz-rapid** [comment]
I'll open a PR soon :)

**Comment by malkiz-rapid** [comment]
please review https://github.com/gvko/db-migrator-distributed/pull/2

**Comment by gvko** [comment]
Nice one! 💪 
Merged! ✅

**Comment by malkiz-rapid** [comment]
@gvko Thanks!
Please let me know when you release a new version to NPM

**Comment by gvko** [comment]
> @gvko Thanks! Please let me know when you release a new version to NPM

@malkiz-rapid just did: `v0.0.4`
Thanks for the contribution!
